/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package turimellaSaiAnvesh_119449_assignment1;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
